"""empty message

Revision ID: 582c0a550f4d
Revises: ba015127a6cc
Create Date: 2022-10-11 15:50:28.386664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582c0a550f4d'
down_revision = 'ba015127a6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealplan', sa.Column('introduction', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mealplan', 'introduction')
    # ### end Alembic commands ###
